### ISSUE TITLE
Index Error in Game Board Matrix

### ISSUE THREAD

**Issue by manderc3** [manderc3/falling-blocks#5]
An index error is triggered when a right movement attempt is made at the far right side of the screen.

`Traceback (most recent call last):
  File "C:\Users\Rachel\Documents\chris_folder\github\falling-blocks\falling-blocks.py", line 220, in <module>
    main()
  File "C:\Users\Rachel\Documents\chris_folder\github\falling-blocks\falling-blocks.py", line 195, in main
    gameBoard.moveDown()
  File "C:\Users\Rachel\Documents\chris_folder\github\falling-blocks\falling-blocks.py", line 37, in moveDown
    if (self.checkVerticalCollision()):
  File "C:\Users\Rachel\Documents\chris_folder\github\falling-blocks\falling-blocks.py", line 69, in checkVerticalCollision
    ((self.matrix[potentialYPos][i.xPos] != 0))):
IndexError: list index out of range`

**Comment by manderc3** [comment]
Issue fixed.
